<a href="https://colab.research.google.com/github/sungna1216/esaa-22-1/blob/main/100_Numpy_exercises_(34~66).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [6]:
import numpy as np
yesterday=np.datetime64('today') - np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today') + np.timedelta64(1)
print(yesterday,today,tomorrow)

2022-03-17 2022-03-18 2022-03-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [7]:
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [8]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [9]:
Z=np.random.uniform(0,10,10)
print(Z-Z%1)
print(Z//1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 9. 8. 2. 6. 0. 5. 9. 4. 2.]
[0. 9. 8. 2. 6. 0. 5. 9. 4. 2.]
[0. 9. 8. 2. 6. 0. 5. 9. 4. 2.]
[0 9 8 2 6 0 5 9 4 2]
[0. 9. 8. 2. 6. 0. 5. 9. 4. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [10]:
Z=np.zeros((5,5))
Z+=np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [11]:
def generate():
  for x in range(10):
    yield x
Z= np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [12]:
Z=np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [13]:
Z=np.random.random(10)
Z.sort()
print(Z)

[0.07474334 0.3248825  0.36082786 0.54584634 0.66223534 0.68345545
 0.73784004 0.74304441 0.79023445 0.97338956]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [14]:
Z=np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [15]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
equal=np.allclose(A,B)
print(equal)
equal=np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [16]:
Z=np.zeros(10)
Z.flags.writeable=False
Z[0]=1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [17]:
Z=np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.96561724 0.47310343 1.18872662 0.35723013 0.32320281 0.873717
 0.81598878 0.98750088 0.4226694  1.03352396]
[1.4846694  1.44745609 0.83140869 0.49532627 0.02270215 0.89598817
 0.45101049 0.05330215 1.52589292 0.81188888]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [18]:
Z=np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[0.49535632 0.         0.45238166 0.02465629 0.80180253 0.68333203
 0.79692802 0.68357376 0.87668455 0.03369226]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [19]:
Z=np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [20]:
X=np.arange(8)
Y=X+0.5
C=1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [21]:
for dtype in [np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [22]:
np.set_printoptions(threshold=float("inf"))
Z=np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [23]:
Z=np.arange(100)
v= np.random.uniform(0,100)
index=(np.abs(Z-v).argmin())
print(Z[index])

59


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [30]:
z = np.zeros(10, [('position', [('x',float),
                                ('y',float)]), 
                  ('color', [('r',float),
                             ('g',float),
                             ('b',float)])])
 
print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [31]:
Z = np.random.random((10,2))
# np.atleat_2d : 입력 배열을 2차원으로 받아들임
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.56490479 0.66802638 0.75962457 0.48654682 0.81048453
  0.84793788 0.19100136 0.45609503 0.3143249 ]
 [0.56490479 0.         0.66362919 0.54019268 0.8125198  0.50004014
  0.60527435 0.43608051 0.28439167 0.60214049]
 [0.66802638 0.66362919 0.         0.25530932 0.40009333 0.37126544
  0.3069463  0.73918622 0.83788664 0.37746308]
 [0.75962457 0.54019268 0.25530932 0.         0.63028101 0.11682549
  0.08837657 0.76756808 0.78005977 0.53712149]
 [0.48654682 0.8125198  0.40009333 0.63028101 0.         0.73508777
  0.69854504 0.64608688 0.8576645  0.21894869]
 [0.81048453 0.50004014 0.37126544 0.11682549 0.73508777 0.
  0.12053148 0.7914285  0.76328787 0.62128162]
 [0.84793788 0.60527435 0.3069463  0.08837657 0.69854504 0.12053148
  0.         0.85419195 0.85618544 0.61979254]
 [0.19100136 0.43608051 0.73918622 0.76756808 0.64608688 0.7914285
  0.85419195 0.         0.26998957 0.44395188]
 [0.45609503 0.28439167 0.83788664 0.78005977 0.8576645  0.76328787
  0.85618544 0.269989

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [32]:
z = np.arange(10, dtype=np.float32)
print(z)
z = z.astype(np.int32, copy=False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [33]:
from io import StringIO
 
# fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
 
Z = np.genfromtxt(s,delimiter=",",dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [34]:
print(Z)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) -1
(1, 2) -1
(1, 3) 7
(1, 4) 8
(2, 0) -1
(2, 1) -1
(2, 2) 9
(2, 3) 10
(2, 4) 11


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [35]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y) # 
sigma, mu = 1.0, 0.0 # 가장 일반적인 정규분포
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [36]:
p=3 # 3개의 요소 배치
z = np.zeros((10,10)) #10x10의 빈 배열 생성
np.put(z, np.random.choice(range(10*10), p, replace=False), 7) #10x10 인덱스 안에서 p(3)만큼을 랜덤으로 선택하여 7을 삽입
print(z)

[[0. 0. 0. 7. 0. 0. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [37]:
x = np.random.rand(5, 10)
print(x)
y = x - x.mean(axis=1,keepdims=True)
print(y)

[[0.38140148 0.35759292 0.54213359 0.58226178 0.47919965 0.6061501
  0.1188802  0.85538406 0.18322677 0.25507874]
 [0.94442082 0.86784163 0.27560856 0.23829852 0.01781848 0.44459967
  0.39501672 0.2787088  0.49549027 0.00255828]
 [0.88351668 0.99347549 0.78242877 0.35760693 0.71414987 0.30188504
  0.8837292  0.3937721  0.88111394 0.56869051]
 [0.47021181 0.63825028 0.59119306 0.87618215 0.74758933 0.72517149
  0.65080815 0.32592859 0.86250287 0.2105977 ]
 [0.50832956 0.0537283  0.74829171 0.671932   0.28168503 0.10322993
  0.08543115 0.24524288 0.7927376  0.1232508 ]]
[[-0.05472945 -0.07853801  0.10600266  0.14613085  0.04306872  0.17001917
  -0.31725073  0.41925313 -0.25290416 -0.18105219]
 [ 0.54838465  0.47180545 -0.12042761 -0.15773766 -0.3782177   0.04856349
  -0.00101945 -0.11732738  0.09945409 -0.39347789]
 [ 0.20747982  0.31743864  0.10639192 -0.31842992  0.03811302 -0.37415181
   0.20769234 -0.28226475  0.20507708 -0.10734634]
 [-0.13963174  0.02840674 -0.01865048  0.2663386  

#### 59. How to sort an array by the nth column? (★★☆)

In [38]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()]) # 행의 두번째(index=1) 원소를 기준으로 정렬 (2, 1, 9 --> 1, 2, 9)

[[1 3 2]
 [3 3 9]
 [9 7 6]]
[[1 3 2]
 [3 3 9]
 [9 7 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [41]:
Z=np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [24]:
Z = np.random.uniform(0,1,10)
z = 0.5
print(Z)
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

[0.66447268 0.76741047 0.98997156 0.69362658 0.48308086 0.77126138
 0.68697325 0.87825281 0.35022313 0.61980514]
0.4830808580716178


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [25]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
print(A, B)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x+y
print(it.operands[2])

[[0 1 2]] [[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [26]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
        
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [27]:
Z = np.ones(10)
a = np.random.randint(0,len(Z),20)
np.add.at(Z,a,1)
print(a)
print(Z)

[9 3 5 2 8 3 1 0 8 4 4 1 5 6 9 8 0 1 1 8]
[3. 5. 2. 3. 3. 3. 2. 1. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [28]:
X = [1,2,3,4,5,6]
I = [1,4,5,6,7,8]
F = np.bincount(I,X)
print(F)

[0. 1. 0. 0. 2. 3. 4. 5. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [29]:
img = np.random.randint(0,2,(16,16,3)).astype(np.ubyte)
F = img[...,0]*(256*256) + img[...,1]*256 + img[...,2]
print(len(np.unique(F)))

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)