<a href="https://colab.research.google.com/github/sungna1216/esaa-22-1/blob/main/Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

머신러닝 알고리즘: 데이터를 기반으로 통계적인 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법을 적용해 데이터 내의 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출해 냅니다. 

[머신러닝의 분류]
- 지도학습
 - 분류
 - 회귀
 - 추천 시스템
 - 시각/음성 감지/인지
 - 텍스트 분석,NLP
- 비지도학습
 - 클러스터링
 - 차원 축소
 - 강화학습
 


**넘파이(NumPy)**

In [1]:
import numpy as np #넘파이 모듈 임포트

array(): 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능을 수행


In [2]:
array1=np.array([1,2,3]) #1차원 array로 3개의 데이터를 가지고 있음
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape) # 행과 열의 수를 튜플형태로 가짐

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [5]:
array2=np.array([[1,2,3],[2,3,4]]) #2차원 array로 2개의 로우와 3개의 칼럼으로 구성되어 6개의 데이터를 가지고 있음
print('array2 type:',type(array2))
print('array2 형태:',array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 형태: (2, 3)


In [6]:
array3=np.array([[1,2,3]]) #1개의 로우와 3개의 칼럼으로 구성된 2차원 데이터
print('array3 type:',type(array3))
print('array3 형태:',array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 형태: (1, 3)


In [7]:
print('array1:{:0}차원,array2:{:1}차원,array3:{:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원,array2:2차원,array3: 2차원


In [8]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array2,array3)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] [[1 2 3]
 [2 3 4]] [[1 2 3]]


만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용합니다. 

In [9]:
#int형과 string형이 섞여 있는 리스트
list2=[1,2,'test'] #int형이 유니코드 문자형으로 변환됨
array2=np.array(list2)
print(array2,array2.dtype)
#int형과 float형이 섞여 있는 리스트
list3=[1,2,3.0] #float64형으로 변환됨
array3=np.array(array3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[[1 2 3]] int64


astype():ndarray내 데이터값의 타입 변경

In [11]:
#int32를 float64로 변환
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)
#다시 int32로 변환
array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)
#float형을 int로 변경할 때 소수점 이하는 없어짐
array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


arange(): range()와 유사한 기능. array를 range()로 표현하는 것

In [12]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


- zeros(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
- ones(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환

함수 인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채웁니다. 


In [13]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


reshape(): ndarray를 특정 차원 및 크기로 변환

In [15]:
array1=np.arange(10)
print('array1:\n', array1)
array2=array1.reshape(2,5)
print('array2:\n',array2)
array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
array1.reshape(4,3) #지정된 사이즈로 변경 불가 시 오류 발생

ValueError: ignored

In [17]:
#-1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해 줌.
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5) #로우 인자가 -1, 칼럼 인자가 5
print('array2 shape:',array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


array2는 array1과 호환될 수 있는 2차원 ndarray로 벼환하되, 고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환하라는 의미. 즉, 10개의 1차원 데이터와 호환될 수 있는 5개의 칼럼에 맞는 로우 개수는 2이므로 2*5의 2차원 ndarray로 변환하는 것.

In [18]:
#10개의 1차원 데이터를 고정된 4개의 칼럼을 가진 로우로는 변경할 수 없기에 에러 발생
array1= np.arange(10)
array4=array1.reshape(-1,4)

ValueError: ignored

[reshape(-1,1)의 쓰임새]
- 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 컬럼을 가진 ndarray로 변환됨을 보장함 

In [19]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist()) #tolist(): 리스트 자료형으로 변환
# 3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array4 shape:',array5.shape)
# 1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array4 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


**넘파이의 ndrray의 데이터 세트 선택하기-인덱싱(Indexing)**

1. 단일 값 추출

In [21]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
print('array1:',array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [22]:
print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [23]:
#데이터 값 수정 가능
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


다차원 ndarray에서 단일 값 추출

In [27]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)
print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [28]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [29]:
array1=np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)
array5=array1[3:]
print(array5)
array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [31]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [32]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


팬시 인덱싱

In [33]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


불린 인덱싱

In [35]:
array1d=np.arange(1,10)
#[]안에 array1d>5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [36]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [37]:
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [38]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:',array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


**행렬의 정렬- sort()와 argsort()**

행렬 정렬
- 넘파이에서 sort()를 호출하는 방식 **np.sort()**: 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환함
- 행렬 자체에서 sort()를 호출하는 방식 **ndarray.sort()**: 원 행렬 자체를 정렬한 형태로 병환하며 반환 값은 None 

In [39]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)
#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 반환된 원본 행렬:',org_array)
#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 반환된 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [40]:
#내림차순으로 정렬
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [42]:
#행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행
array2d=np.array([[8,12],[7,1]])

sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


정렬된 행렬의 인덱스를 반환하기
- np.argsort(): 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [43]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [44]:
# 내림차순으로 정렬
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [45]:
#argsort()의 활용도(ex: 시험 성적순으로 학생이름 출력하기)
name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])
sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


행렬 내적(행렬 곱)

In [46]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


전치 행렬

In [47]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
